<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Page Title Area
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="page-title-area bg-white-smoke">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="page-header-content text-center">
                            <div class="page-header-caption">
                                <h2 class="page-title">About us</h2>
                            </div><!--~~./ page-header-caption ~~-->
                            <div class="breadcrumb-area">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="./">Home</a></li>  
                                    <li class="breadcrumb-item active">About Us</li>
                                </ol>
                            </div><!--~~./ breadcrumb-area ~~-->
                        </div><!--~~./ page-header-content ~~-->
                    </div>
                </div>
            </div><!--~~./ end container ~~-->
        </div><!--~~./ end page title area ~~--> 

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start About Us Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="about-us-block ptb-120">
            <div class="container">
                <!-- Title Row -->
                <div class="row align-items-center">
                    <div class="col-lg-5">
                        <div class="mock-up-thumb md-mrb-55">
                            <img src="assets/images/about/about.png" alt="About Mock" />
                        </div><!-- /.mock-up-block -->
                    </div><!-- /.col-lg-5 -->
                    
                    <div class="col-lg-6">
                        <div class="about-text-content">
                            <div class="section-title">
                                <h2 class="title-main">About <span>Yanga Bid</span></h2><!-- /.title-main -->
                            </div><!-- /.section-title -->
                            <div class="about-info-list">
                                <div class="single-info">
                                    <div class="icon">
                                        <span class="icon-like1"></span>
                                    </div><!-- /.icon -->
                                    <div class="info">
                                        <h3 class="heading">Mission</h3>
                                        <p>To make auctioning a pleasant and benefiting experience</p>
                                    </div><!-- /.info -->
                                </div><!-- /.single-info -->
                                
                                <div class="single-info">
                                    <div class="icon">
                                        <span class="icon-review-1"></span>
                                    </div><!-- /.icon -->
                                    <div class="info">
                                        <h3 class="heading">Vision</h3>
                                        <p>To provide an efficient and interactive platform that multiplies revenue for charitable purposes</p>
                                    </div><!-- /.info -->
                                </div><!-- /.single-info -->
                            </div>
                        </div>
                    </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end about us block ~~-->

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Fan Fact Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="fanfact-block bg-white-smoke ptb-120">
            <div class="container ml-b-30">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="section-title">
                            <h2 class="title-main" data-animate="hg-fadeInUp">our <span>strategy</span></h2><!-- /.title-main -->
                        </div><!-- /.section-title -->
                        <div class="fanfact-content pd-r-70 ml-t-10">
                            <p>We’re a fast-paced bidding auction platform where you can win some of your favorite, genuine items by bidding. We’re not the traditional "going once, going twice" auctions that you may be familiar with. Yanga bid is Nigeria’s first foray into naira auctions on a large scale.</p>
                        </div>
                    </div>
                    
                </div>
            </div><!-- /.container -->
        </div><!--~~./ end fanfact block ~~-->
		