<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Page Title Area
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="page-title-area bg-white-smoke">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="page-header-content text-center">
                            <div class="page-header-caption">
                                <h2 class="page-title">Contact Us</h2>
                            </div><!--~~./ page-header-caption ~~-->
                            <div class="breadcrumb-area">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="./">Home</a></li>  
                                    <li class="breadcrumb-item active">contact</li>
                                </ol>
                            </div><!--~~./ breadcrumb-area ~~-->
                        </div><!--~~./ page-header-content ~~-->
                    </div>
                </div>
            </div><!--~~./ end container ~~-->
        </div><!--~~./ end page title area ~~--> 

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Contact Info Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="contact-info-block ptb-120">
            <div class="container ml-b-30">
                <div class="row">
                    <div class="col-lg-4 col-md-6">  
                        <div class="contact-info-item address" data-animate="hg-fadeInUp">
                            <div class="shape-icon">
                                <span class="icon-map2"></span>
                            </div>
                            
                            <div class="card-info">
                                <p>34, Ilorin Street, Masha, Surulere, <strong>LAGOS</strong></p>
                                <p>12 Samora Machel, Asokoro, <strong>ABUJA</strong></p>
                            </div><!-- /.card-info -->
                        </div><!-- /.contact-info-item -->
                    </div><!-- /.col-lg-4 -->

                    <div class="col-lg-4 col-md-6">  
                        <div class="contact-info-item email" data-animate="hg-fadeInUp">
                            <div class="shape-icon">
                                <span class="icon-email-1"></span>
                            </div>
                            <div class="card-info">
                                <p><a href="mailto:talk2us@yangabid.com">talk2us@yangabid.com</a></p>
                                <p><a href="mailto:yangabid21@gmail.com">yangabid21@gmail.com</a></p>
                            </div><!-- /.card-info -->                           
                        </div><!-- /.contact-info-item -->
                    </div><!-- /.col-lg-4 -->

                    <div class="col-lg-4 col-md-6">  
                        <div class="contact-info-item" data-animate="hg-fadeInUp">
                            <div class="shape-icon">
                                <span class="icon-phone"></span>
                            </div>
                            <div class="card-info">
                                <p>07062013791, 07062013792, 07062013793, 07016429634</p>
                            </div><!-- /.card-info -->
                        </div><!-- /.contact-info-item -->
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end contact info block ~~-->

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Contact Form Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="contact-form-block pd-b-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="contact-form-area">
                            <div class="section-title">
                                <h2 class="title-main hg-fadeInUp animated" data-animate="hg-fadeInUp" style="visibility: visible;">Get In <span>Touch</span></h2><!-- /.title-main -->
                            </div>
                            <form id="contact_form" class="contact-form" action="#">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input class="form-controller" id="name" name="name" type="name" placeholder="Your Name">
                                        </div>
                                    </div><!--./ col-lg-6 -->
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input class="form-controller" id="email" name="email" type="email" placeholder="Your Email">
                                        </div>
                                    </div><!--./ col-lg-6 -->
                                    <div class="col-12">
                                        <div class="form-group">
                                            <textarea id="message" name="message" class="form-controller" rows="4" cols="50" placeholder="Type Your Message"></textarea>
                                        </div>
                                    </div><!-- /.col-12 -->
                                    <div class="col-12 mrt-5">
                                        <button type="submit" class="btn btn-default">Submit now</button>
                                    </div><!--./ col-lg-6 -->
                                </div><!-- /.row -->
                            </form><!-- /.contact-form -->
                        </div><!-- /.contact-form-area -->
                    </div><!-- /.col-lg-8 -->
                    <div class="col-lg-4">
                        <div class="contact-thumb md-mrt-60" data-animate="hg-fadeInLeft">
                            <img src="assets/images/others/contact.png" alt="Thumbnail">
                        </div>
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end contact form block ~~-->