<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Page Title Area
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="page-title-area bg-white-smoke">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="page-header-content text-center">
                            <div class="page-header-caption">
                                <h2 class="page-title">frequently asked questions</h2>
                            </div><!--~~./ page-header-caption ~~-->
                            <div class="breadcrumb-area">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="./">Home</a></li>  
                                    <li class="breadcrumb-item active">FAQs</li>
                                </ol>
                            </div><!--~~./ breadcrumb-area ~~-->
                        </div><!--~~./ page-header-content ~~-->
                    </div>
                </div>
            </div><!--~~./ end container ~~-->
        </div><!--~~./ end page title area ~~-->

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Faqs Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="faqs-block pd-b-120">
            <div class="container">
                <div class="row flex-wrap-reverse">
                    <div class="col-lg-6">
                        <div class="faq-thumb md-mrt-55" data-animate="hg-fadeInLeft">
                            <img src="assets/images/others/faq1.png" alt="Thumbnail">
                        </div>
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <div class="faq-wrapper ml-b-15">
                            <div class="faq-item open active">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">What is yangabid?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>Yangabid is an efficient and user-friendly platform that multiples funds for charitable purposes through auctioning of sponsored items.</p>
                                </div>
                            </div><!-- /.faq-item -->

                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How do I bid on an item?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>The following steps will be taken before bidding on an item on www.yangabid.com:
                                    <ul>
                                        <li>Sign up/register with your email and phone number to activate your account.</li>
                                        <li>Pay for your gate fee valid for 1 day / 24hrs
                                        <li>Get your free bids</li>
                                        <li>Click on home page to see auction items</li>
                                        <li>Select your preferred item and start bidding by inputting numbers between 1 and 500</li>
                                        <li>click on the bid button below.</li>
                                    </ul>
                                    Repeat same process as many times as possible.
                                    
                                </div>
                            </div><!-- /.faq-item -->

                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How long does a bidding section last?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>When the time attached to the item expires.</p>
                                </div>
                            </div><!-- /.faq-item -->

                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How many times can I bid on an item?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>You can bid on an item as many times as you can as long as you have a bidding power(bid pack) to become the highest bidder.</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">Can I bid on multiple items at the same auction period?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>Yes, you can bid on multiple items at the same auction period.</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How long are bids valid?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>Bids expires after one (1) hour.</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How can I increase my chances of winning?
</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>Continue bidding on your favorite item(s).</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">Are there limits to how often I can bid?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>No, you can bid as often as you can.</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How do I claim my wins?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>A congratulatory message will be sent to your registered phone number/email address and follow up call.</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">How long do I have after winning to claim my win?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>Not more than 48 hours. </p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">What happens when two winners emerge at the end of an 
auction?
</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>We will create a new auction for them alone.</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            <div class="faq-item">
                                <div class="faq-title">
                                    <span class="icon-file-text"></span>
                                    <h4 class="title">What is the difference between instant and live auction?</h4>
                                    <span class="right-icon"></span>
                                </div>
                                <div class="faq-content">
                                    <p>An instant auction is an auction done live at a particular location by yanagbid representatives within a few minutes. WHILE, A live auction is an auction on the website which last for a period of time for people to bid from their houses, offices etc...</p>
                                </div>
                            </div><!-- /.faq-item -->
                            
                            
                        </div><!-- /.faq-wrapper -->
                    </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end faqs block ~~-->