<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Site Footer
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <footer class="site-footer pd-t-120">
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                Start Footer Widget Area
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
            <div class="footer-widget-area">
                <div class="container">
                    <div class="row">
                        <!--~~~~~ Start Widget About us ~~~~~--> 
                        <div class="col-lg-4">
                            <aside class="widget widget_about">
                                <h2 class="widget-title">About Us</h2>
                                <div class="widget-content">
                                    <p>Nigeria's leading online naira auction platform for high quality products and offerings to help you afford your best life.</p>
                                    <div class="contact-info">
                                        <div class="p-1 mr-2 icon" style="background:#fff;">
                                            <span class="icon-paperplane"></span>
                                        </div>
                                        <div class="info">
                                            <p>Nigeria</p>
                                        </div>
                                    </div><!-- /.contact-info -->
                                    <div class="contact-info">
                                        <div  class="p-1 mr-2 icon" style="background:#fff;">
                                            <span class="icon-phone2"></span>
                                        </div>
                                        <div class="info">
                                            <p>07062013791, 07062013792, 07062013793, 07016429634</p>
                                        </div>
                                    </div><!-- /.contact-info -->
                                    <div class="contact-info">
                                        <div class="p-1 mr-2 icon" style="background:#fff;">
                                            <span class="icon-mail5"></span>
                                        </div>
                                        <div class="info">
                                            <p><a href="mailto:talk2us@yangabid.com">talk2us@yangabid.com</a><br /><a href="mailtoyangabid21@gmail.com">yangabid21@gmail.com</a></p>
                                        </div>
                                    </div><!-- /.contact-info -->
                                    <div class="contact-info">
                                        <div class="p-1 mr-2 icon" style="background:#fff;">
                                            <span class="fab fa-instagram" style="color:#833AB4"></span>
                                        </div>
                                        <div class="info">
                                            <p><a href="https://www.instagram.com/yangabidthe_100market/">@yangabidthe_100market</a></p>
                                        </div>
                                    </div><!-- /.contact-info -->
                                    <div class="contact-info">
                                        <div class="p-1 mr-2 icon" style="background:#fff;">
                                            <span class="fab fa-facebook" style="color:#4267B2"></span>
                                        </div>
                                        <div class="info">
                                            <p><a href="https://www.facebook.com/people/Yangabid-the-100-market/100073335940125/">Yangabid the #100 market</a></p>
                                        </div>
                                    </div><!-- /.contact-info -->
                                    <div class="contact-info">
                                        <div class="p-1 mr-2 icon" style="background:#fff;">
                                            <span class="fab fa-youtube" style="color:#FF0000"></span>
                                        </div>
                                        <div class="info">
                                            <p><a href="https://www.youtube.com/channel/UCwtggrGNpfTieeVx0eQcbTA">Yangabid the #100 market</a></p>
                                        </div>
                                    </div><!-- /.contact-info -->
                                    
                                </div>
                            </aside>
                        </div><!--~./ end about us widget ~-->
                        
                        <!--~~~~~ Start Widget Links ~~~~~--> 
                        <div class="col-lg-2">
                            <aside class="widget widget_links">
                                <h2 class="widget-title">Quick Link</h2>
                                <div class="widget-content">   
                                    <ul>
                                        <li><a href=".?page=tou">Terms and Condition</a></li>
                                        
                                        
                                        <li><a href=".?page=what-is-yangabid">What is Yangabid?</a></li>
                                    </ul>
                                </div>
                            </aside>
                        </div><!--~./ end links widget ~-->

                        <!--~~~~~ Start Widget Links ~~~~~--> 
                        <div class="col-lg-2">
                            <aside class="widget widget_links">
                                <h2 class="widget-title">Help Center</h2>
                                <div class="widget-content">
                                    <ul>
                                        <li><a href=".?page=faq">FAQ</a></li>
                                        <li><a href=".?page=how-it-works">How It Works On Yangabid</a></li>
                                        
                                    </ul>
                                </div>
                            </aside>
                        </div><!--~./ end links widget ~-->

                        <!--~~~~~ Start Widget Links ~~~~~--> 
                        <div class="col-lg-4">
                            <aside class="widget widget_payment">
                                <h2 class="widget-title">Payment Option</h2>
                                <div class="widget-content">
									<div class="payment-accepted">
										<img src="assets/images/payment/payment-method.png" alt="Payment method">
									</div>
                                </div>
                                <hr />
                                <div><img src="assets/images/logo/hon-logo.PNG"  class="img-fluid" style="height:40px"/>
                                <p><strong>HON Foundation Partner</strong><br />Every profit goes to charity</p></div>
                            </aside>
                        </div><!--~./ end payment widget ~-->
                    </div>
                </div>
            </div><!--~./ end footer widgets area ~-->

            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                Start Footer Bottom Area
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
            <div class="footer-bottom-area">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="copyright-text text-center">
                                <p>Copyright  © Yangabid 2021. All rights reserved</p>
                            </div><!--~./ end copyright text ~-->
                        </div><!--~./ col-12 ~-->
                    </div>
                </div>
            </div><!--~./ end footer bottom area ~-->
        </footer><!--~./ end site footer ~-->
    </div><!--~~./ end site content ~~-->
	<div class="modal fade" id="bidModal" tabindex="-1" role="dialog" aria-labelledby="bidModalLabel" aria-hidden="true">
		<div class="modal-dialog bg-white-smoke" role="document">
			<div class="modal-content">
				<div class="modal-header" style="border-bottom:none;">
					<button type="button" class="close close-bid-modal" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body bid-output">
				...
				</div>
				<!--
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Save changes</button>
				</div>
				-->
			</div>
		</div>
	</div>

    <!-- All The JS Files
    ================================================== --> 
	<script src="assets/js/all.min.js"></script>
    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/jquery.countdown.min.js"></script>
    <script src="assets/js/plugins.js"></script>
    <script src="assets/js/meanmenu.min.js"></script>
    <script src="assets/js/particles.min.js"></script>
    <script src="assets/js/imagesloaded.pkgd.min.js"></script> 
    <script src="assets/js/jquery.nice-select.min.js"></script> 
    <script src="assets/js/theia-sticky-sidebar.min.js"></script>
    <script src="assets/js/ResizeSensor.min.js"></script>
    <script src="assets/js/simple-scrollbar.min.js"></script>
    <script src="assets/js/scrolla.jquery.min.js"></script>
    <script src="assets/js/odometer.min.js"></script>
    <script src="assets/js/isInViewport.jquery.js"></script>
    <script src="assets/js/yscountdown.min.js"></script>
    <script src="assets/js/owl.carousel.min.js"></script>
    <script src="assets/js/main.js"></script>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="assets/js/engine.js?build=<?php echo mt_rand(); ?>"></script><!-- main-js -->
</body>
</html>