<?php @session_start(); ?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Page Title Area
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="page-title-area bg-white-smoke">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="page-header-content text-center">
                            <div class="page-header-caption">
                                <h2 class="page-title">How It Works On Yangabid</h2>
                            </div><!--~~./ page-header-caption ~~-->
                            <div class="breadcrumb-area">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="./">Home</a></li>  
                                    <li class="breadcrumb-item active">How it Works</li>
                                </ol>
                            </div><!--~~./ breadcrumb-area ~~-->
                        </div><!--~~./ page-header-content ~~-->
                    </div>
                </div>
            </div><!--~~./ end container ~~-->
        </div><!--~~./ end page title area ~~--> 

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            User Signin Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="user-signup-block ptb-120">
            <div class="bg-left bg-image" style="background-image: url('assets/images/shape/signup-shape.png')"></div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h4 style="color:#EEEE12; margin-bottom:25px; text-align:center;">How to win your dream items on www.yangabid.com</h4>
                        <h4><ol>
<li>
Log into <a href="www.yangabid.com">www.yangabid.com</a> from your preferred browser. 
</li>
<li>Click on Sign up Icon.<br />
<img src="assets/images/others/signup.jpg" class="img responsive" />
</li>
<li>Fill the form below and click sign up<br />
<img src="assets/images/others/reg-form.png" class="img responsive" />
</li>
<li>Enter the code sent to your registered phone number/email address below to complete your registration. <br />
<img src="assets/images/others/activate.jpg" class="img responsive" />
</li>
<li>Fill the form below and click sign up<br />
<img src="assets/images/others/reg-form.png" class="img responsive" />
</li>
<li>Get pass<br />
<img src="assets/images/others/get-pass.jpg" class="img responsive" />
</li>
<li>Get Bid<br />
<img src="assets/images/others/get-bid.jpg" class="img responsive" />
</li>
<li>On auction listing, click on preferred item<br />
<img src="assets/images/others/auction.jpg" class="img responsive" />
</li>
<li>Input a number between 1-500<br />
<img src="assets/images/others/bid.jpg" class="img responsive" />
</li>
<li>
    After bidding, close the dialog and keep bidding on other items
</li>
                        </ol></h4>

					</div>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end user signup block ~~-->