<?php @session_start(); ?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Page Title Area
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="page-title-area bg-white-smoke">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="page-header-content text-center">
                            <div class="page-header-caption">
                                <h2 class="page-title">What is Yangabid</h2>
                            </div><!--~~./ page-header-caption ~~-->
                            <div class="breadcrumb-area">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="./">Home</a></li>  
                                    <li class="breadcrumb-item active">What is Yangabid</li>
                                </ol>
                            </div><!--~~./ breadcrumb-area ~~-->
                        </div><!--~~./ page-header-content ~~-->
                    </div>
                </div>
            </div><!--~~./ end container ~~-->
        </div><!--~~./ end page title area ~~--> 

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            User Signin Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="user-signup-block ptb-120">
            <div class="bg-left bg-image" style="background-image: url('assets/images/shape/signup-shape.png')"></div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
						<h4>What is Yangabid?</h4>
<p>Yangabid is an auction market where sponsors donate auction items and bidders play for first place. It is an efficient and user friendly platform that multiplies funds for charity purposes through the auctioning of sponsored items. Our mission is to make auctioning a pleasant and benefitting experience. Yangabid is a non political, social or religious group.</p>
<p>yangabid.com is an auction site that brings the craziest deals straight to your phone, tablets and pc. On yangabid.com , you can bid for the coolest stuffs and pay next to nothing. The principle behind yangabid is amazing . You DO NOT pay for the items after bidding. Here is how it works. At the beginning of a bidding section, you will be notified of the items up for bid. These range from smart phones, cash prices, airtime, household equipments and so much more...</p>
<p>The bidder with the "HIGHEST NUMBER" is simply the person that places the most amount of bids at the end of the bid session. So if you place more bids than any other bidder during the bidding session, you "WIN" it's that simple.</p>

					</div>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end user signup block ~~-->