	<!-- common libraries. required for every page-->
	<script src="lib/jquery/dist/jquery.min.js"></script>
	<script src="lib/jquery-pjax/jquery.pjax.js"></script>
	<script src="lib/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
	<script src="lib/widgster/widgster.js"></script>
	<script src="lib/underscore/underscore.js"></script>

	<!-- common application js -->
	<script src="js/app.js"></script>
	<script src="js/settings.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
</body>
</html>