<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Hero Block
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<div id="hero-block" class="hero-block bg-overlay bg-image" style="background-image: url('assets/images/bg/hero.jpg')">
	<div id="particles-js"></div>
	<div class="container">
		<div class="row align-items-center justify-content-center hero-content-main">
			<div class="col-lg-8">
				<div class="hero-content-area text-center ptb-120">
					<div class="hero-title-area">
						<h2 class="hero-title">Bidzone Auction Bidding Platform</h2><!-- /.hero-title -->
					</div><!-- /.hero-title-area -->
					<div class="hero-desc">
						<p>Join the community and stay up to date on the latest deals and auctions.</p>
					</div><!-- /.hero-desc -->
					<div class="form-group-btn">
						<a class="btn btn-default" href=".?page=auction">All Auction</a>
						<a class="btn btn-default btn-white" href=".?page=about">Learn more</a>
					</div><!-- /.form-group-btn -->
				</div><!-- /.hero-content-area -->
			</div><!-- /.col-lg-8 -->
		</div><!--  /.row -->
	</div><!-- /.container -->
</div><!-- /.hero-block -->

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Facility Area
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="facility-area">
            <div class="container ml-b-30">
                <div class="row facility-content">
                    <div class="col-lg-3 col-md-6">
                        <div class="facility-box">
                            <div class="icon">
                                <span class="fa fa-user"></span>
                            </div>
                            <h3 class="title">Sign Up</h3>
							<p>Join the community and stay up to date on the latest deals and auctions.</p>
                        </div><!-- /.facility-box -->
                    </div><!-- /.col-lg-3 -->
                    <div class="col-lg-3 col-md-6">
                        <div class="facility-box">
                            <div class="icon">
                                <span class="icon-coin-dollar"></span>
                            </div>
                            <h3 class="title">Purchase a BidPack</h3>					
							<p>Be ready to go toe-to-toe with other bidders for what you like.</p>
                        </div><!-- /.facility-box -->
                    </div><!-- /.col-lg-3 -->
                    <div class="col-lg-3 col-md-6">
                        <div class="facility-box">
                            <div class="icon">
                                <span class="icon-credit-card"></span>
                            </div>
                            <h3 class="title">Start Bidding</h3>
							<p>Choose an auction to participate in and click “bid now”.</p>
                        </div><!-- /.facility-box -->
                    </div><!-- /.col-lg-3 -->
                    <div class="col-lg-3 col-md-6">
                        <div class="facility-box">
                            <div class="icon">
                                <span class="fa fa-box"></span>
                            </div>
                            <h3 class="title">Claim Win/Buy It Now</h3>
							<p>Claim your win or "Buy It Now" and have it delivered to you.</p>
                        </div><!-- /.facility-box -->
                    </div><!-- /.col-lg-3 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- /.facility-area -->
		
		

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Live Auction Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="live-auction-block bg-white-smoke ptb-120">
            <div class="container ml-b-30">
                <div class="row justify-content-center">
                    <div class="col-lg-9">
                        <div class="section-title text-center">
                            <h2 class="title-main" data-animate="hg-fadeInUp">live <span>Auction</span></h2><!-- /.title-main -->
                        </div><!-- /.section-title -->
                    </div><!-- /.col-lg-9 -->
                </div><!-- /.row -->

                <div class="row items-two-1199">
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item">
                            <div class="item-header">
                                <h3 class="heading"><a href="auction-details.html">JBL GO Digital Drone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-footer -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product1.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product2.jpg" alt="Thumbnail">
                                </a>
                                <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-price">$0.08</div>
                                    <div class="bid-timer-area">
                                        <div id="bid_counter1" class="bid-timer"></div>
                                        <p>Waiting For Bid</p>
                                    </div>
                                </div>
                                <div class="bid-button">
                                    <a class="btn btn-default" href="index.html#">Bid Now</a>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item">
                            <div class="item-header">
                                <h3 class="heading"><a href="auction-details.html">BBB Bluetooth Headphone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-footer -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product4.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product3.jpg" alt="Thumbnail">
                                </a>
                                <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-price">$0.66</div>
                                    <div class="bid-timer-area">
                                        <div id="bid_counter2" class="bid-timer"></div>
                                        <p>Waiting For Bid</p>
                                    </div>
                                </div>
                                <div class="bid-button">
                                    <a class="btn btn-default" href="index.html#">Bid Now</a>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item">
                            <div class="item-header">
                                <h3 class="heading"><a href="auction-details.html">Android Mobile Phone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-footer -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product5.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product6.jpg" alt="Thumbnail">
                                </a>
                                <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-price">$0.55</div>
                                    <div class="bid-timer-area">
                                        <div id="bid_counter3" class="bid-timer"></div>
                                        <p>Waiting For Bid</p>
                                    </div>
                                </div>
                                <div class="bid-button">
                                    <a class="btn btn-default" href="index.html#">Bid Now</a>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item">
                            <div class="item-header">
                                <h3 class="heading"><a href="auction-details.html">Digital Headphone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-footer -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product3.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product4.jpg" alt="Thumbnail">
                                </a>
                                <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-price">$0.15</div>
                                    <div class="bid-timer-area">
                                        <div id="bid_counter4" class="bid-timer"></div>
                                        <p>Waiting For Bid</p>
                                    </div>
                                </div>
                                <div class="bid-button">
                                    <a class="btn btn-default" href="index.html#">Bid Now</a>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item">
                            <div class="item-header">
                                <h3 class="heading"><a href="auction-details.html">Realistic Watche</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-footer -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product7.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product8.jpg" alt="Thumbnail">
                                </a>
                                <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-price">$0.15</div>
                                    <div class="bid-timer-area">
                                        <div id="bid_counter5" class="bid-timer"></div>
                                        <p>Waiting For Bid</p>
                                    </div>
                                </div>
                                <div class="bid-button">
                                    <a class="btn btn-default" href="index.html#">Bid Now</a>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item">
                            <div class="item-header">
                                <h3 class="heading"><a href="auction-details.html">JBL GO White Drone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-footer -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product2.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product1.jpg" alt="Thumbnail">
                                </a>
                                <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-price">$0.33</div>
                                    <div class="bid-timer-area">
                                        <div id="bid_counter6" class="bid-timer"></div>
                                        <p>Waiting For Bid</p>
                                    </div>
                                </div>
                                <div class="bid-button">
                                    <a class="btn btn-default" href="index.html#">Bid Now</a>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
            </div>
        </div><!-- /.live-auction-block -->

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Upcomming Auction Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="upcoming-auction-block ptb-120">
            <div class="container ml-b-30">
                <div class="row justify-content-center">
                    <div class="col-lg-9">
                        <div class="section-title text-center">
                            <h2 class="title-main" data-animate="hg-fadeInUp">Upcoming <span>Auction</span></h2><!-- /.title-main -->
                        </div><!-- /.section-title -->
                    </div><!-- /.col-lg-9 -->
                </div><!-- /.row -->

                <div class="row">
                    <div class="col-12">
                        <div class="upcoming-auction-main">
                            <div class="upcoming-auction-carousel carousel-nav-dots owl-carousel">
                                <div class="auction-item style-two">
                                    <div class="item-img">
                                        <a href="index.html#">
                                            <img src="assets/images/auction/grid/product1.jpg" alt="Thumbnail">
                                            <img class="prod2" src="assets/images/auction/grid/product2.jpg" alt="Thumbnail">
                                        </a>
                                        <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                        <div class="item-price">Price: $339</div>
                                    </div><!-- /.item-img -->
                                    <div class="item-header">
                                        <h3 class="heading"><a href="index.html#">JBL GO Digital Drone</a></h3>
                                        <div class="auction-id">Auction ID: BB28111</div>
                                    </div><!-- /.item-header -->
                                </div><!-- /.auction-item -->
                                <div class="auction-item style-two">
                                    <div class="item-img">
                                        <a href="index.html#">
                                            <img src="assets/images/auction/grid/product4.jpg" alt="Thumbnail">
                                            <img class="prod2" src="assets/images/auction/grid/product3.jpg" alt="Thumbnail">
                                        </a>
                                        <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                        <div class="item-price">Price: $339</div>
                                    </div><!-- /.item-img -->
                                    <div class="item-header">
                                        <h3 class="heading"><a href="index.html#">BBB Bluetooth Headphone</a></h3>
                                        <div class="auction-id">Auction ID: BB28111</div>
                                    </div><!-- /.item-header -->
                                </div><!-- /.auction-item -->
                                <div class="auction-item style-two">
                                    <div class="item-img">
                                        <a href="index.html#">
                                            <img src="assets/images/auction/grid/product5.jpg" alt="Thumbnail">
                                            <img class="prod2" src="assets/images/auction/grid/product6.jpg" alt="Thumbnail">
                                        </a>
                                        <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                        <div class="item-price">Price: $339</div>
                                    </div><!-- /.item-img -->
                                    <div class="item-header">
                                        <h3 class="heading"><a href="index.html#">Android Mobile Phone</a></h3>
                                        <div class="auction-id">Auction ID: BB28111</div>
                                    </div><!-- /.item-header -->
                                </div><!-- /.auction-item -->
                                <div class="auction-item style-two">
                                    <div class="item-img">
                                        <a href="index.html#">
                                            <img src="assets/images/auction/grid/product3.jpg" alt="Thumbnail">
                                            <img class="prod2" src="assets/images/auction/grid/product4.jpg" alt="Thumbnail">
                                        </a>
                                        <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                        <div class="item-price">Price: $339</div>
                                    </div><!-- /.item-img -->
                                    <div class="item-header">
                                        <h3 class="heading"><a href="index.html#">Digital Headphone</a></h3>
                                        <div class="auction-id">Auction ID: BB28111</div>
                                    </div><!-- /.item-header -->
                                </div><!-- /.auction-item -->
                                <div class="auction-item style-two">
                                    <div class="item-img">
                                        <a href="index.html#">
                                            <img src="assets/images/auction/grid/product7.jpg" alt="Thumbnail">
                                            <img class="prod2" src="assets/images/auction/grid/product8.jpg" alt="Thumbnail">
                                        </a>
                                        <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                        <div class="item-price">Price: $339</div>
                                    </div><!-- /.item-img -->
                                    <div class="item-header">
                                        <h3 class="heading"><a href="index.html#">Realistic Watche</a></h3>
                                        <div class="auction-id">Auction ID: BB28111</div>
                                    </div><!-- /.item-header -->
                                </div><!-- /.auction-item -->
                                <div class="auction-item style-two">
                                    <div class="item-img">
                                        <a href="index.html#">
                                            <img src="assets/images/auction/grid/product2.jpg" alt="Thumbnail">
                                            <img class="prod2" src="assets/images/auction/grid/product1.jpg" alt="Thumbnail">
                                        </a>
                                        <div class="bid-max">3 x <span class="icon-user-1"></span></div>
                                        <div class="item-price">Price: $339</div>
                                    </div><!-- /.item-img -->
                                    <div class="item-header">
                                        <h3 class="heading"><a href="index.html#">JBL GO White Drone</a></h3>
                                        <div class="auction-id">Auction ID: BB28111</div>
                                    </div><!-- /.item-header -->
                                </div><!-- /.auction-item -->
                            </div><!-- /.upcoming-auction-carousel -->
                        </div><!-- /.upcoming-auction-main -->
                    </div>
                </div><!-- /.row -->
            </div>
        </div><!-- /.upcoming-auction-block -->

        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Closed Auction Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="closed-auction-block bg-white-smoke ptb-120">
            <div class="container ml-b-30">
                <div class="row justify-content-center">
                    <div class="col-lg-9">
                        <div class="section-title text-center">
                            <h2 class="title-main" data-animate="hg-fadeInUp">closed <span>Auction</span></h2><!-- /.title-main -->
                        </div><!-- /.section-title -->
                    </div><!-- /.col-lg-9 -->
                </div><!-- /.row -->

                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item style-three">
                            <div class="item-header">
                                <h3 class="heading"><a href="index.html#">Digital Headphone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-header -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product3.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product4.jpg" alt="Thumbnail">
                                </a>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-status">Closed</div>
                                    <div class="bid-winner">Davidames</div>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item style-three">
                            <div class="item-header">
                                <h3 class="heading"><a href="index.html#">Realistic Watche</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-header -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product7.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product8.jpg" alt="Thumbnail">
                                </a>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-status">Closed</div>
                                    <div class="bid-winner">Davidames</div>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="auction-item style-three">
                            <div class="item-header">
                                <h3 class="heading"><a href="index.html#">JBL GO White Drone</a></h3>
                                <div class="auction-id">Auction ID: BB28111</div>
                            </div><!-- /.item-header -->
                            <div class="item-img">
                                <a href="index.html#">
                                    <img src="assets/images/auction/grid/product2.jpg" alt="Thumbnail">
                                    <img class="prod2" src="assets/images/auction/grid/product1.jpg" alt="Thumbnail">
                                </a>
                                <div class="item-price">Price: $339</div>
                            </div><!-- /.item-img -->
                            <div class="item-footer">
                                <div class="item-footer-top">
                                    <div class="bid-status">Closed</div>
                                    <div class="bid-winner">Davidames</div>
                                </div>
                            </div><!-- /.item-footer -->
                        </div><!-- /.auction-item -->
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
            </div>
        </div><!-- /.closed-auction-block -->
		
		
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            Start Win Steps Block
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <div class="win-steps-block ptb-150">
            <div class="container ml-b-45">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="section-title text-center">
                            <h2 class="title-main" data-animate="hg-fadeInUp">Easy 3 Steps <span>To Win</span></h2><!-- /.title-main -->
                        </div><!-- /.section-title -->
                    </div><!-- /.col-lg-1 -->
                </div><!-- /.row -->

                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="card-center">
                            <div class="card-icon">
                                <img src="assets/images/icon/select.png" alt="Icon">
                                <div class="step">01</div>
                            </div>
                            <div class="card-info">
                                <h3 class="heading">Choose product</h3>
                                <p>All our products are brand new, top shelf items from your favourite brands. You want it, we’ve got it</p>
                            </div><!-- /.card-info -->
                        </div><!-- /.card-center -->
                    </div><!-- /.col-lg-4 -->

                    <div class="col-lg-4 col-md-6">
                        <div class="card-center">
                            <div class="card-icon">
                                <img src="assets/images/icon/auction.png" alt="Icon">
                                <div class="step">02</div>
                            </div>
                            <div class="card-info">
                                <h3 class="heading">Bid product</h3>
                                <p>Our model is created to make your bidding experience easy and rewarding. Just click “bid now”.</p>
                            </div><!-- /.card-info -->
                        </div><!-- /.card-center -->
                    </div><!-- /.col-lg-4 -->

                    <div class="col-lg-4 col-md-6">
                        <div class="card-center">
                            <div class="card-icon">
                                <img src="assets/images/icon/trophy.png" alt="Icon">
                                <div class="step">03</div>
                            </div>
                            <div class="card-info">
                                <h3 class="heading">Easy Win</h3>
                                <p>You bid fast, and we deliver even faster. Everything is sharp sharp, fast fast, and now now</p>
                            </div><!-- /.card-info -->
                        </div><!-- /.card-center -->
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!--~~./ end win steps block ~~-->